### ISSUE TITLE
Community site design issue

### ISSUE THREAD

**Issue by gyulaszucs** [SenseNet/sensenet.github.io#104]
Side menu design bugs occurs when width<1430px :
![image](https://user-images.githubusercontent.com/13551768/29414116-01593b62-835f-11e7-877b-ebe500f7738c.png)
![image](https://user-images.githubusercontent.com/13551768/29414142-194f314a-835f-11e7-902c-7000b73d1aec.png)

**Comment by herflis** [comment]
fixed
