### ISSUE TITLE
Best practices for your first sensenet ECM project

### ISSUE THREAD

**Issue by balazskeszei** [SenseNet/sensenet.github.io#107]
Create a summary for those who like to try sensenet ECM but don't want to read the whole wiki for quick hints.
Parts (examples):
- installation
- modules of the software
- create a content library / workplace(?)
- set up users (?)
- manipulate the views of the content/site

this will be a summary/guide that links to multiple wiki sites (for more details).

**Comment by tusmester** [comment]
Closed as obsolete.
