### ISSUE TITLE
[Guide] Content List

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#214]
Create a short introduction about the Content Lists in general. The [current version](https://github.com/SenseNet/sensenet.github.io/blob/redesign-docs/guide/_guides/content-list.md) contains text from the docs currently published on the community site but it should be reviewed and rewritten to be a bit less detailed.

**Comment by viragumathe5** [comment]
Hey Hi @herflis I am sorry but I really didn't understand  the language in that content page is it just a template or something like that 
It would be great if you help me with it 

Thank You

**Comment by herflis** [comment]
Hi, @viragumathe5,
yes it contains placeholder text (just like lorem ipsum, but from [ulysses](http://joyceipsum.com/ulysses/))
Are you searching for a suitable hacktoberfest task? 🙂

**Comment by viragumathe5** [comment]
Actually I am done with my 4 PR and now trying to  get into some deeper problems 

@herflis just want to tell you I tried in google language detector for that text and trying to convert it in every language so that I can understand it lol

**Comment by herflis** [comment]
Poor [James Joyce](https://en.wikipedia.org/wiki/James_Joyce) 😅 Anyway [Ulysses](https://www.goodreads.com/book/show/338798.Ulysses) is worth reading, @viragumathe5 give the book a chance! 😉

**Comment by viragumathe5** [comment]
I am so idiot 

Let it be Thank You so much will definitely contribute

**Comment by 7wikd** [comment]
Mind if I pick up this task? Could someone provide me with the details?
