### ISSUE TITLE
Searching in guide docs UX questions

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sensenet.github.io#221]
Found the following problems/questions that might need some UX/UI consideration/guideance/ideas:

- [x] Access more than 10 results: Might need to add function to search beyond the first 10 hits. At present important results easily remain hidden. Example: user searches for 'content', but the most relevant article, 'Content' (guide/content-repository/content), is not listed. So we could display 10, but we might want use some form of scrolling or paging so that user can search on for more results.

- [x] Typing should not collapse the tree: Typing in search box collapses all branches of the tree. Whole tree remains collapsed even after search box is cleared. If I refresh the page, however, the subtree I was in before, expands again.

- [x] Browse subtrees without switching to other pages: Would be nice to be able to browse subtrees without leaving the page I'm reading at the moment. If I am reading a page but would like to have a look at the items under another subtree, clicking the subtree parent loads the associated page. Perhaps we could place an icon before the parent items that expand the subtree, without leaving my current page.

**Comment by CsabaPeter** [comment]
Accessing to more than 10 results can be done similar to Ebay's or Amazon's solution. Only a few choices are apparent by default but when a user clicks on the more/show more button more results will be available. 
![ebaytree](https://user-images.githubusercontent.com/38352683/43079272-e8cc327c-8e8c-11e8-9a5e-2a6efd8ff774.png)

**Comment by CsabaPeter** [comment]
The tree should be left uncollapsed until the user hits enter in the search bar. After the user conducted the search the tree structure should update to the current state of the search (eg. highlighted where the user is at the given moment) but remain uncollapsed and browsable even after the site is refreshed. The tree only should be collapsed or being in it's original state when the user closes and reopens the window.

**Comment by CsabaPeter** [comment]
Totally agree. It should be highlighted where the user is at the moment, but he should browse the tree independently and change the page only when he clicks on the article

**Comment by kultsar** [comment]
2 and 3 ok, added 2 new issues for implementation.
About 1: in the example you showed we have a full (finished) list after clicking show more, What if our search result list is much longer? Should we again have a show more link at the bottom? If yes, what should happen to the beginnning of the list? Should we have a scroll bar, or some other solution?
