### ISSUE TITLE
Browse subtrees without switching to other pages

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sensenet.github.io#226]
Would be nice to be able to browse subtrees without leaving the page I'm reading at the moment. If I am reading a page but would like to have a look at the items under another subtree, clicking the subtree parent loads the associated page. Perhaps we could place an icon before the parent items that expand the subtree, without leaving my current page.

UX agrees: "It should be highlighted where the user is at the moment, but he should browse the tree independently and change the page only when he clicks on the article."

**Comment by tusmester** [comment]
Closed as obsolete.
