### ISSUE TITLE
docs dashboard

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#267]
![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/2d4fce5b-8d0f-4ec8-bafb-b76d2507e9f3)

**Comment by CsabaPeter** [comment]
Sample:
![Web 1920 – 1](https://user-images.githubusercontent.com/38352683/62784398-ac5f7380-babe-11e9-92a7-1e6f808e79af.png)
