### ISSUE TITLE
[docs] Version info on the admin-ui

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#284]
We need a simple guide for enduser about version info screen 
1. accessing the version info screen
2. how to use the available information
3. ...

admin-ui can be reached at [admin.sensenet.com](https://admin.sensenet.com)
username: Builtin\admin
password: admin
repository url: https://dev.demo.sensenet.com

![image.png](https://images.zenhubusercontent.com/58d2263651aa2c3057792558/abe00168-4fd2-48ee-8b2f-8aaafe994ec3)

**Comment by kylesalk** [comment]
I can help out with this one!

**Comment by herflis** [comment]
Hi @kylesalk I assigne this on you then :)

**Comment by kylesalk** [comment]
Is there a specific branch I should start from? It looks like develop (and other develop branches) and master are very different with doc structure.

**Comment by zoltanbedi** [comment]
Hi @kylesalk use the master branch please.
