### ISSUE TITLE
[docs] Saved searches and the search result page on the admin-ui

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#285]
We need a simple guide for enduser about the screen with the search result and saved searches
1. accessing the search screen
2. run a simple search
3. access the search results
4. save a search result
5. re-run a saved search

admin-ui can be reached at [admin.sensenet.com](https://admin.sensenet.com)
username: Builtin\admin
password: admin
repository url: https://dev.demo.sensenet.com (if it does not work, try https://devservice.demo.sensenet.com)

![image](https://user-images.githubusercontent.com/6968860/66041238-b54a4f80-e519-11e9-9b19-4743f4b4aaa1.png)

**Comment by jaded3** [comment]
Hi. I'd like to work on this issue. But I'm not able to log in with the above credentials.

**Comment by herflis** [comment]
Welcome @jaded3, sorry, the mentioned demo site is currently under maintanence, I've added another url to use it if the main demo is not working

**Comment by vinamrbajaj** [comment]
Is the issue open

**Comment by Sumindar** [comment]
hi i am new to open source but want to contribute in documentation please guide

**Comment by xShuden** [comment]
Hi. I'd like to work on this issue. @herflis
