### ISSUE TITLE
[tutorials] Update MVC tutorial

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#286]
The [Getting started with sensenet and MVC
](https://community.sensenet.com/docs/tutorials/starting-out-with-mvc/) tutorial should be reviewed and since the _sn-webpages_ package is obsolete all of its occurences should be deleted

**Comment by greenorb007** [comment]
Basically we have to remove all the things related to "snadmin install-webpages" right. Am i picked it right please tell i am beginner to the open source.
Is "https://github.com/SenseNet/sensenet.github.io/blob/master/_docs/install-webpages-from-nuget.md"
this repo is correct to look for changes

**Comment by greenorb007** [comment]
Do i remove all the links from sensenet.webpages and sn-webpages from  NuGet

**Comment by herflis** [comment]
Hi @greenorb007 the main goal of this issue is to try out the tutorial without installing sn-webpages (so skip the steps with sn-webpages) and if it is working, then the related text can be removed from this tutorial. Did you complete the tutorial?

**Comment by codetronaut** [comment]
@herflis I have created a pull request at #288 please review it if it's valid or not.
Thanks

**Comment by greenorb007** [comment]
Thanks @codetronaut btw , i was little confused so i stopped working on this issue.

**Comment by greenorb007** [comment]
@herflis please check the PR created by @codetronaut  if it's not correct than i can try it.

**Comment by codetronaut** [comment]
@herflis Please assign me this issue as I am working on this and please do check #288 for the same.
