### ISSUE TITLE
[docs] Broken link in dashborad.md

### ISSUE THREAD

**Issue by kn-neelalohitha** [SenseNet/sensenet.github.io#299]
# What happened?
While I was going through [dashboard.md](https://github.com/SenseNet/sensenet.github.io/blob/master/_docs/admin-ui/dashboard.md) I found a broken link for **personal-settings**
# What you expect to happen?
The expected behaviour is redirecting to [personal-settings.md](https://github.com/SenseNet/sensenet.github.io/blob/master/_docs/admin-ui/personal-settings.md)

**Comment by thatrobotdev** [comment]
Fixed in #306

**Comment by zoltanbedi** [comment]
Honestly I don't see this broken link. In https://community.sensenet.com/docs/admin-ui/dashboard/
when I click the personal settings link it navigates to https://community.sensenet.com/docs/admin-ui/personal-settings/ this page which is correct.

I'm going to close this issue and your prs. Thanks for your work anyway.
