### ISSUE TITLE
Port documentation from Wiki: Viewing documents in the browser

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#301]
Port old article from wiki and refresh them for sensenet 7. The new article should be an .md file in the sensenet repository's /docs folder. Old screenshots should be remaked on the new admin-ui if it is possible and placed into the /docs/images folder.

The .md file should have the following header:

```
---
title: %title%
source_url: %url of the file on github%
category: Guide
version: v7.0.0
tags: %possible tags as an array%
---
```

(you can use [the docs here](https://github.com/SenseNet/sensenet.github.io/tree/master/_docs) as example)

[Viewing documents in the browser](http://wiki.sensenet.com/Viewing_documents_in_the_browser)

**Comment by brittanyjoiner15** [comment]
Hi! I'm new to editing docs, but I'd be happy to help. Where do I find this original wiki to copy over? I just tried clicking wiki on here and it didnt bring anything up.

**Comment by herflis** [comment]
Hi @brittanyjoiner15,
this issue is already taken, but we have a similar one related to docs [here](https://github.com/SenseNet/sensenet/issues/686). Check it out and if you have any questions, feel free to ask 🙂

**Comment by A1zippo1** [comment]
> 
> 
> Hi @brittanyjoiner15,
> this issue is already taken, but we have a similar one related to docs [here](https://github.com/SenseNet/sensenet/issues/686). Check it out and if you have any questions, feel free to ask 🙂

Hi @herflis . I'd also love to help with some issue but I'm a beginner to git. Could you explain me how can I "take" an issue to work on it?
Thank you for this chance and for your time

**Comment by herflis** [comment]
Hy @A1zippo1 , I've just added a bunch of issue, that can be good for beginners 🙂 Check them out 👉 [here](https://github.com/SenseNet/sensenet.github.io/labels/hacktoberfest)
