### ISSUE TITLE
Typo in /_docs/content.md file

### ISSUE THREAD

**Issue by anuragsachdeva28** [SenseNet/sensenet.github.io#304]
Grammatical and typing mistakes in content.md file.

**Comment by zoltanbedi** [comment]
General issues like this is not needed really and don't have any value for us. If you find a typo it is better to open a pr with a fix.

**Comment by anuragsachdeva28** [comment]
> General issues like this is not needed really and don't have any value for us. If you find a typo it is better to open a pr with a fix.

I have opened a PR for the same.
