### ISSUE TITLE
Fix mixed content issue

### ISSUE THREAD

**Issue by zoltanbedi** [SenseNet/sensenet.github.io#309]
The CI to netlify fails with mixed content. https://github.com/SenseNet/sensenet.github.io/pull/308/checks?check_run_id=249201268

- [x] Download the img from the [link](http://wiki.sensenet.com/images/f/f8/Becnhmark-02.png) and move it to /img/posts
- [x] Change the url in _docs/benchmark-details.md

**Comment by digikin** [comment]
Lem me try this one.

**Comment by zoltanbedi** [comment]
I'm not sure which pr to choose right now, but please don't open duplicate pr-s. If you want to work on some issue just comment on the issue. This way people will not send multiple pr-s for one issue.

**Comment by zoltanbedi** [comment]
Here is what I'm going to do. I'll merge @andreidavid pr because he created the fix first.
I found some more mixed content if you could resolve those @digikin that would be awsome.
Here are the remaining urls that needs https instead of http.
https://app.netlify.com/sites/community-sensenet/deploys/5d9b4645080e00000804fc4d

- [ ] /blog/2016/02/01/enchancing-the-copy-experience-in-sn7
- [ ] /blog/2016/02/18/3-things-you-will-love-in-sense-net-smartphone-app
- [ ] /blog/2016/04/01/card-sorting-results-the-new-structure-of-portlets-in-sn7
- [ ] /blog/2016/05/04/rethinking-the-survey-feature
- [ ] /blog/2016/08/26/permission-overview-tool-making-sense-of-your-permission-nightmare
- [ ] /blog/2016/10/27/redesigning-sensenet-com-find-the-sn7-story-of-yours
- [ ] /blog/2017/07/05/what-is-a-headless-cms

**Comment by zoltanbedi** [comment]
Fixed in #357
