### ISSUE TITLE
[deployment] docs.service.sensenet.com build

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#349]
- [x] install sensenet services
- [x] create a demo folder structure for docs
- [x] import the .md files from [sensenet.github.io/_docs](https://github.com/SenseNet/sensenet.github.io/tree/master/_docs) into the sensenet repo
- [x] the files should be re-imported every time when something is pushed into the sensenet.github.io repository's master branch

**Comment by VargaJoe** [comment]
I can do this.
