### ISSUE TITLE
Contributed for Hacktoberfest - Error 404 Not found

### ISSUE THREAD

**Issue by crisgit** [SenseNet/sensenet.github.io#396]
When contributing to this repository, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change.

So I checked that address: 

https://community.sensenet.com/docs/admin-ui/command-palette/

In the part described to click:

> Is something missing? See something that needs fixing? I propose to change **here.**

Redirect to Url does not exist:

https://github.com/SenseNet/sensenet.github.io/blob/master/docs/admin-ui/command-palette.md

**Comment by herflis** [comment]
Hey @crisgit ,
thank you for bringing this to our attention! As we work to fix the link, you can find the document [here](https://github.com/SenseNet/sensenet.github.io/blob/master/_docs/admin-ui/command-palette.md)
