### ISSUE TITLE
[docs] docs.sensenet.com mainpage design cr-s

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#409]
- [x] the upper  three boxes should be for groups API docs, Tutorials and Example apps
- [x] the other three boxes should be for groups Concepts, Admin-ui and Integrations
- [x] place links to 'quickstart', 'troubleshooting', 'contact us', gitter, stackoverflow
- [x] create a screen for mobilephones as well
- [x] put a link to 'release notes' somewhere
- [x] change box 'integrations' to 'use cases and best practices', sublinks in this box should be now '1000 content' demo & '25.000 content' demo

**Comment by CsabaPeter** [comment]
https://xd.adobe.com/view/cfd2c088-b00c-4c2b-7a4c-44f3465f8c90-b9e3/
