### ISSUE TITLE
[blogpost] sensenet.com redesign

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#442]

**Comment by nileshhazra** [comment]
Can I work on this redesign of blog ?

**Comment by nileshhazra** [comment]
Please provide a little description on expecting changes and may be the link to the website repo. @herflis

**Comment by herflis** [comment]
Hi @nileshhazra, it is already assigned to @CsabaPeter , please choose an issue on the [dedicated board](https://github.com/orgs/SenseNet/projects/7)
