### ISSUE TITLE
Feature request: Add SEO plugin

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet.github.io#48]
It is possible to add SEO functionality to Jekyll pages. This would be really helpful for us, since our blog is here as well.

You can find more info about the SEO Tag plugin here: https://github.com/jekyll/jekyll-seo-tag

**Comment by herflis** [comment]
@borsi The mentioned plugin was added earlier but as a plus i've added a [sitemap generator plugin](https://github.com/SenseNet/sensenet.github.io/pull/77) and a [robots.txt](https://github.com/SenseNet/sensenet.github.io/pull/78) file. Are them enough as SEO improvement for now? Are there any other idea related to this topic?

**Comment by borsi** [comment]
Not yet, thanks. 👍
